import type { Metadata } from "next";
import { Bebas_Neue, Inter, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { HeaderComponent } from "@/components/header";
import FooterComponent from "@/components/Layout/Footer";

const roboto = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title: "interior-design",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-white ${roboto.className}`}>
        <HeaderComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
