import type { Metadata } from "next";
import { Bebas_Neue, Inter } from "next/font/google";
import "./globals.css";
import { HeaderComponent } from "@/components/header";

export const metadata: Metadata = {
  title: "interior-design",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black">
        <HeaderComponent />
        {children}
      </body>
    </html>
  );
}
